#!/bin/bash

HOSTNAME=$(hostname)
USERNAME=$(whoami)
DATETIME=$(date)


echo "System Information"

echo "------------------"

#Gather system information

OS_INFO=$(source /etc/os-release && echo "$NAME $VERSION")
UPTIME=$(uptime -p)
CPU_INFO=$(lscpu | grep "Model name")
RAM_INFO=$(free -h | awk '/Mem:/ {print $2}')
DISK_INFO=$(lsblk -o MODEL,SIZE | grep -v "MODEL")
VIDEO_INFO=$(lspci | grep -i vga | awk -F: '{print $2}')
HOST_IP=$(ip -4 a | awk '/global/ {print $2}')  
GATEWAY_IP=$(ip route | grep default | awk '{print $3}')
DNS_SERVER=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}')

#show system status
LOGGED_USERS=$(who | awk '{print $1}' | sort | uniq)
DISK_SPACE=$(df -h | awk '{print $6, $4}')
PROCESS_COUNT=$(ps aux | wc -l)
LOAD_AVG=$(uptime | awk -F'load average:' '{print $2}')
LISTENING_PORTS=$(ss -tuln | awk '{print $5}' | cut -d: -f2 | sort -n | uniq | paste -sd ",")
UFW_STATUS=$(sudo ufw status | head -n 1)


cat <<EOF

System Report for $HOSTNAME generated by $USERNAME, on $DATETIME

System Information
------------------
OS: $OS_INFO
Uptime: $UPTIME
CPU: $CPU_INFO
RAM: $RAM_INFO
Disk(s): $DISK_INFO
Video: $VIDEO_INFO
Host Address: $HOST_IP
Gateway IP: $GATEWAY_IP
DNS Server: $DNS_SERVER

System Status
-------------
Users Logged In: $LOGGED_USERS
Disk Space: $DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVG
Listening Network Ports: $LISTENING_PORTS
UFW Status: $UFW_STATUS

EOF
